// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI9_5KkvfDIKxODw3dTmR3G4Ff88bX_5o',
    appId: '1:995626493389:web:7d7b4da865f9cb1cfb9084',
    messagingSenderId: '995626493389',
    projectId: 'aasc-mideo',
    authDomain: 'aasc-mideo.firebaseapp.com',
    storageBucket: 'aasc-mideo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYwt8qiagC7Jq8_FKIhJ2CP1opyEiDf1k',
    appId: '1:995626493389:android:35a73ee5ae49382cfb9084',
    messagingSenderId: '995626493389',
    projectId: 'aasc-mideo',
    storageBucket: 'aasc-mideo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH79vrSBWhzOkrk1GSvXvUdhITlQLml1o',
    appId: '1:995626493389:ios:e6c68a35c9691908fb9084',
    messagingSenderId: '995626493389',
    projectId: 'aasc-mideo',
    storageBucket: 'aasc-mideo.appspot.com',
    iosBundleId: 'com.example.test01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH79vrSBWhzOkrk1GSvXvUdhITlQLml1o',
    appId: '1:995626493389:ios:e6c68a35c9691908fb9084',
    messagingSenderId: '995626493389',
    projectId: 'aasc-mideo',
    storageBucket: 'aasc-mideo.appspot.com',
    iosBundleId: 'com.example.test01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI9_5KkvfDIKxODw3dTmR3G4Ff88bX_5o',
    appId: '1:995626493389:web:2c55a12e32b298f4fb9084',
    messagingSenderId: '995626493389',
    projectId: 'aasc-mideo',
    authDomain: 'aasc-mideo.firebaseapp.com',
    storageBucket: 'aasc-mideo.appspot.com',
  );

}